In [2]:
import os

In [3]:
print(os.listdir())

['.ipynb_checkpoints', 'Final.csv', 'first.ipynb', 'second.ipynb', 'test.csv', 'train.csv']


In [4]:
import numpy as np
import pandas as pd

In [5]:
#Loading the Train Dataset 
train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')

In [6]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
#Creating a copy of the dataset
data=train_data

In [12]:
# Droping the unneccseary Columns from the dataset
data=train_data.drop(columns=["Name","Ticket","Cabin"])

In [66]:
data

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
888          889         0       3  female   NaN      1      2  23.4500   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
888        S  
889        C  
890        Q  

[891 rows x 9 columns]

In [13]:
#Appling Feature Scalling to column "Sex"
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Sex"]=le.fit_transform(data["Sex"])

In [14]:
data

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    1  22.0      1      0   7.2500        S
1              2         1       1    0  38.0      1      0  71.2833        C
2              3         1       3    0  26.0      0      0   7.9250        S
3              4         1       1    0  35.0      1      0  53.1000        S
4              5         0       3    1  35.0      0      0   8.0500        S
..           ...       ...     ...  ...   ...    ...    ...      ...      ...
886          887         0       2    1  27.0      0      0  13.0000        S
887          888         1       1    0  19.0      0      0  30.0000        S
888          889         0       3    0   NaN      1      2  23.4500        S
889          890         1       1    1  26.0      0      0  30.0000        C
890          891         0       3    1  32.0      0      0   7.7500        Q

[891 rows x 9 columns]

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null int32
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int32(1), int64(5), object(1)
memory usage: 59.3+ KB


In [17]:
data["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [22]:
# As there are only 3 null values in the Embarked so  we will delete those rows
data.dropna(subset=["Embarked"],inplace=True)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    889 non-null int64
Survived       889 non-null int64
Pclass         889 non-null int64
Sex            889 non-null int32
Age            889 non-null float64
SibSp          889 non-null int64
Parch          889 non-null int64
Fare           889 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int32(1), int64(5), object(1)
memory usage: 66.0+ KB


In [24]:
# Replacing all the null values of Age with mean 
data["Age"].fillna(data["Age"].mean(),inplace=True)

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    889 non-null int64
Survived       889 non-null int64
Pclass         889 non-null int64
Sex            889 non-null int32
Age            889 non-null float64
SibSp          889 non-null int64
Parch          889 non-null int64
Fare           889 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int32(1), int64(5), object(1)
memory usage: 66.0+ KB


In [26]:
##Appling Feature Scalling to column "Embarked"

data["Embarked"]=le.fit_transform(data["Embarked"])

In [27]:
data

PassengerId  Survived  Pclass  Sex        Age  SibSp  Parch     Fare  \
0              1         0       3    1  22.000000      1      0   7.2500   
1              2         1       1    0  38.000000      1      0  71.2833   
2              3         1       3    0  26.000000      0      0   7.9250   
3              4         1       1    0  35.000000      1      0  53.1000   
4              5         0       3    1  35.000000      0      0   8.0500   
..           ...       ...     ...  ...        ...    ...    ...      ...   
886          887         0       2    1  27.000000      0      0  13.0000   
887          888         1       1    0  19.000000      0      0  30.0000   
888          889         0       3    0  29.642093      1      2  23.4500   
889          890         1       1    1  26.000000      0      0  30.0000   
890          891         0       3    1  32.000000      0      0   7.7500   

     Embarked  
0           2  
1           0  
2           2  
3           2  
4           2  
..        ...  
886         2  
887         2  
888         2  
889         0  
890         1  

[889 rows x 9 columns]

In [29]:
y=data.iloc[:,1].values

In [30]:
data_new=data.drop(columns=["Survived","PassengerId"])

In [31]:
data_new

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    1  22.000000      1      0   7.2500         2
1         1    0  38.000000      1      0  71.2833         0
2         3    0  26.000000      0      0   7.9250         2
3         1    0  35.000000      1      0  53.1000         2
4         3    1  35.000000      0      0   8.0500         2
..      ...  ...        ...    ...    ...      ...       ...
886       2    1  27.000000      0      0  13.0000         2
887       1    0  19.000000      0      0  30.0000         2
888       3    0  29.642093      1      2  23.4500         2
889       1    1  26.000000      0      0  30.0000         0
890       3    1  32.000000      0      0   7.7500         1

[889 rows x 7 columns]

In [32]:
X=data_new.iloc[:,0:].values

In [33]:
X


array([[ 3.       ,  1.       , 22.       , ...,  0.       ,  7.25     ,
         2.       ],
       [ 1.       ,  0.       , 38.       , ...,  0.       , 71.2833   ,
         0.       ],
       [ 3.       ,  0.       , 26.       , ...,  0.       ,  7.925    ,
         2.       ],
       ...,
       [ 3.       ,  0.       , 29.6420927, ...,  2.       , 23.45     ,
         2.       ],
       [ 1.       ,  1.       , 26.       , ...,  0.       , 30.       ,
         0.       ],
       [ 3.       ,  1.       , 32.       , ...,  0.       ,  7.75     ,
         1.       ]])

In [34]:
from sklearn.model_selection import train_test_split 
from sklearn import tree
from sklearn.metrics import accuracy_score

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [36]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [37]:

prediction=clf.predict(X_test)
prediction

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [38]:
print("Accuracy is-",accuracy_score(y_test,prediction)*100)

Accuracy is- 76.40449438202246


In [88]:
test_data


PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [39]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [40]:
data_new=test_data.drop(columns=["Name","Ticket","Cabin","PassengerId"])

In [41]:

data_new

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [42]:
data_new["Sex"]=le.fit_transform(data_new["Sex"])

In [43]:
data_new

Pclass  Sex   Age  SibSp  Parch      Fare Embarked
0         3    1  34.5      0      0    7.8292        Q
1         3    0  47.0      1      0    7.0000        S
2         2    1  62.0      0      0    9.6875        Q
3         3    1  27.0      0      0    8.6625        S
4         3    0  22.0      1      1   12.2875        S
..      ...  ...   ...    ...    ...       ...      ...
413       3    1   NaN      0      0    8.0500        S
414       1    0  39.0      0      0  108.9000        C
415       3    1  38.5      0      0    7.2500        S
416       3    1   NaN      0      0    8.0500        S
417       3    1   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [44]:
data_new['Embarked'].describe()


count     418
unique      3
top         S
freq      270
Name: Embarked, dtype: object

In [45]:
common_value = 'S'
data = [data_new]

for dataset in data:
    dataset['Embarked'] = dataset['Embarked'].fillna(common_value)

In [46]:
data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
Pclass      418 non-null int64
Sex         418 non-null int32
Age         332 non-null float64
SibSp       418 non-null int64
Parch       418 non-null int64
Fare        417 non-null float64
Embarked    418 non-null object
dtypes: float64(2), int32(1), int64(3), object(1)
memory usage: 21.4+ KB


In [47]:
data_new["Age"].fillna(data_new["Age"].mean(),inplace=True)
data_new["Fare"].fillna(data_new["Fare"].mean(),inplace=True)



In [113]:
data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
Pclass      418 non-null int64
Sex         418 non-null int32
Age         418 non-null float64
SibSp       418 non-null int64
Parch       418 non-null int64
Fare        418 non-null float64
Embarked    418 non-null object
dtypes: float64(2), int32(1), int64(3), object(1)
memory usage: 21.4+ KB


In [48]:
data_new

Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0         3    1  34.50000      0      0    7.8292        Q
1         3    0  47.00000      1      0    7.0000        S
2         2    1  62.00000      0      0    9.6875        Q
3         3    1  27.00000      0      0    8.6625        S
4         3    0  22.00000      1      1   12.2875        S
..      ...  ...       ...    ...    ...       ...      ...
413       3    1  30.27259      0      0    8.0500        S
414       1    0  39.00000      0      0  108.9000        C
415       3    1  38.50000      0      0    7.2500        S
416       3    1  30.27259      0      0    8.0500        S
417       3    1  30.27259      1      1   22.3583        C

[418 rows x 7 columns]

In [49]:
data_new["Embarked"]=le.fit_transform(data_new["Embarked"])

In [50]:
data_new

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1  34.50000      0      0    7.8292         1
1         3    0  47.00000      1      0    7.0000         2
2         2    1  62.00000      0      0    9.6875         1
3         3    1  27.00000      0      0    8.6625         2
4         3    0  22.00000      1      1   12.2875         2
..      ...  ...       ...    ...    ...       ...       ...
413       3    1  30.27259      0      0    8.0500         2
414       1    0  39.00000      0      0  108.9000         0
415       3    1  38.50000      0      0    7.2500         2
416       3    1  30.27259      0      0    8.0500         2
417       3    1  30.27259      1      1   22.3583         0

[418 rows x 7 columns]

In [51]:
X_test_new=data_new.iloc[:,0:].values

In [52]:
X_test_new

array([[ 3.        ,  1.        , 34.5       , ...,  0.        ,
         7.8292    ,  1.        ],
       [ 3.        ,  0.        , 47.        , ...,  0.        ,
         7.        ,  2.        ],
       [ 2.        ,  1.        , 62.        , ...,  0.        ,
         9.6875    ,  1.        ],
       ...,
       [ 3.        ,  1.        , 38.5       , ...,  0.        ,
         7.25      ,  2.        ],
       [ 3.        ,  1.        , 30.27259036, ...,  0.        ,
         8.05      ,  2.        ],
       [ 3.        ,  1.        , 30.27259036, ...,  1.        ,
        22.3583    ,  0.        ]])

In [53]:
# Fitting the test dataset in the model.
prediction=clf.predict(X_test_new)
prediction

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [54]:
arr1=test_data["PassengerId"].values
arr1

array([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1040, 1041, 10

In [55]:
arr2=prediction

In [56]:
arr2

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [57]:
arr1 = arr1.reshape((418,1))

In [58]:
arr1

array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [59]:
arr2 = arr2.reshape((418,1))

In [60]:
arr2

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

In [61]:
Final_dataset=np.concatenate((arr1,arr2),axis=1)

In [62]:
Final_dataset

array([[ 892,    0],
       [ 893,    0],
       [ 894,    1],
       [ 895,    1],
       [ 896,    1],
       [ 897,    0],
       [ 898,    1],
       [ 899,    1],
       [ 900,    1],
       [ 901,    0],
       [ 902,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    1],
       [ 910,    0],
       [ 911,    0],
       [ 912,    1],
       [ 913,    1],
       [ 914,    1],
       [ 915,    1],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    0],
       [ 920,    1],
       [ 921,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    1],
       [ 925,    0],
       [ 926,    1],
       [ 927,    1],
       [ 928,    0],
       [ 929,    0],
       [ 930,    0],
       [ 931,    1],
       [ 932,    0],
       [ 933,    1],
       [ 934,    1],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    1],
       [ 939,

In [63]:
pd.DataFrame(Final_dataset).to_csv("Final.csv")